#!/bin/sh

#  config.yml
#  Created by Mathilde Brossard on 2024-05-08.


# Path to the folder containing the dataset :
path_data: /Users/mathilde/Desktop/Precision_stopms_sct_COPY_4/data

# Path to save the output :
path_output: /Users/mathilde/Desktop/Precision_stopms_sct_COPY_4/output

# Path to the script :
path_script: /Users/mathilde/Desktop/Precision_stopms_sct_COPY_4/Script_batch_processing_1.sh

# Each subject folder starts with a prefix:
subject_prefix: "sub-"

# In order to include all sessions of each subject
include_sessions: true

